### ISSUE TITLE
Interpolation modifies values in curly brackets

### ISSUE THREAD

**Issue by avaika** [joeatbayes/file2consul#1]
I'm using latest file2consul from master (commit e8c4814a3551d8b3d16fc447f86fbc1faa37354c).

**Current behavior**:

Values in curly brackets are converted to lowercase if no variable is available for replacement whenever interpolation is enabled. Thus file2consul uploads unexpected value to consul.
E.g. entry in property file like this:
```
custom_key = {ABcdE}
```
will be uploaded to consul like this `{abcde}`. 

**Expected behavior**:
Interpolation doesn't change the value to lowercase and uploads to consul the value as it is `{ABcdE}`. Or at the very least we should state in the documentation, that interpolation changes the values in curly brackets to lowercase.

--

Could you please have a look into the issue?

**Comment by joeatbayes** [comment]
go ahead and make the change to support this and submit a pull requst
